credentials:
  usernames:
    tjm.plastica:
      email: tjm.plastica@gmail.com
      name: Thiago Jung
      password: $2b$12$3YaJs8IsoADGTL.PJnt5aeWWvSuad.QZXmTxBqVnDJOnCJjlAoRo. # To be replaced with hashed password
    dr.thiagojung:
      email: dr.thiagojung@gmail.com
      name: Gabi
      password: $2b$12$SyQpGqcwuOLT14XoU.XnEOkLez6J8JPvQ5gbL4iUOMQ9ZBbOIMAYC # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: bla_bla_voila # Must be string
  name: dr_thiago_cookie
preauthorized:
  emails:
  - tjm.plastica@gmail.com